name: github-actions-sample

on:
  pull_request:
    branches: master

jobs:
  Github-Actions-Sample:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Greeting
        id: greeting
        run: |
          chmod +x .github/scripts/greet.sh
          .github/scripts/greet.sh

      - name: Run Here
        id: here
        if: steps.greeting.outputs.GREETING_STATUS == '0'
        run: |
          chmod +x .github/scripts/here.sh
          .github/scripts/here.sh

      - name: Run Fatal
        id: fatal
        if: steps.here.outputs.HERE_STATUS == '0'
        run: |
          chmod +x .github/scripts/fatal.sh
          .github/scripts/fatal.sh

      - name: Run Bye
        id: bye
        if: steps.fatal.outputs.FATAL_STATUS == '0'
        run: |
          chmod +x .github/scripts/bye.sh
          .github/scripts/bye.sh

      - name: PR comment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GREET_OUTPUT: ${{ steps.greeting.outputs.GREETING }}
          HERE_OUTPUT: ${{ steps.here.outputs.HERE  }}
          BYE_OUTPUT: ${{ steps.bye.outputs.BYE }}
        run: |
          chmod +x .github/scripts/pr_comment.sh
          .github/scripts/pr_comment.sh

      - name: Faild
        if: |
          steps.greeting.outputs.GREETING_STATUS != '0' ||
          steps.here.outputs.HERE_STATUS != '0' ||
          steps.here.outputs.FATAL_STATUS != '0' ||
          steps.bye.outputs.BYE_STATUS != '0'
        run: exit 1
