name: github-actions-sample

on:
  pull_request:
    branches: master

jobs:
  Github-Actions-Sample:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Greeting
        id: greeting
        run: |
          output=$(make greeting 2>&1 || true)
          echo "GREETING<<EOF" >> $GITHUB_OUTPUT
          echo "$output" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Run Here
        id: here
        run: |
          output=$(make here 2>&1 || true)
          echo "HERE<<EOF" >> $GITHUB_OUTPUT
          echo "$output" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Run Bye
        id: bye
        run: |
          output=$(make bye 2>&1 || true)
          echo "BYE<<EOF" >> $GITHUB_OUTPUT
          echo "$output" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: PR comment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          greet="${{ steps.greeting.outputs.GREETING }}"
          here="${{ steps.here.outputs.HERE }}"
          bye="${{ steps.bye.outputs.BYE }}"

          greet_escaped=$(printf "%s\n" "$greet" | sed 's/`/\\`/g')
          here_escaped=$(printf "%s\n" "$here" | sed 's/`/\\`/g')
          bye_escaped=$(printf "%s\n" "$bye" | sed 's/`/\\`/g')

          gh pr comment ${{ github.event.pull_request.number }} --body "
          ### Greeting

          <details>
          <summary>結果を見る</summary>

          \`\`\`
          $greet_escaped
          \`\`\`

          </details>

          ### Here

          <details>
          <summary>結果を見る</summary>

          \`\`\`
          $here_escaped
          \`\`\`

          </details>

          ### Bye

          <details>
          <summary>結果を見る</summary>

          \`\`\`
          $bye_escaped
          \`\`\`

          </details>
          "
